# must be unique in a given SonarQube Server instance
sonar.projectKey=Registro-de-Energia
sonar.token=sqp_85a91c8013b54a9fc8715538c500b54fd3874626

sonar.source=src
sonar.exclusions=**/test/**

sonar.tests=test