# must be unique in a given SonarQube Server instance
sonar.projectKey=Registro-de-Energia
sonar.token=sqp_85a91c8013b54a9fc8715538c500b54fd3874626

# --- optional properties ---

# defaults to project key
#sonar.projectName=My project
# defaults to 'not provided'
#sonar.projectVersion=1.0
 
# Path is relative to the sonar-project.properties file. Defaults to .
#sonar.sources=.
 
# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8